accelerate launch --gpu_ids 0,1 --config_file=../recipes/zero2.yaml --num_processes 2 ../run/grpo_dp.py \
    --model_name_or_path Qwen/Qwen2.5-1.5B \
    --max_prompt_length 1900 \
    --max_completion_length 2048 \
    --gradient_accumulation_steps 1 \
    --dataset_name /home/sanupam/efficient_reasoning/data/MBPPPlus/train.jsonl \
    --dataset_train_split train \
    --per_device_train_batch_size 2 \
    --num_generations 4 \
    --seed 42 \
    --output_dir results/original_grpo_1.5B \
    --bf16 True \
    --use_vllm True \
    --scale_reward True \
    --save_steps 1000 \
    --save_strategy steps \
    --logging_steps 1 \
    --loss_type dr_grpo
