accelerate launch --gpu_ids 0,1 --config_file=../recipes/zero2.yaml --num_processes 2 ../run/grpo_dp.py \
    --model_name_or_path Qwen/Qwen2.5-0.5B \
    --max_prompt_length 1024 \
    --max_completion_length 2048 \
    --gradient_accumulation_steps 32 \
    --dataset_name /home/sanupam/efficient_reasoning/data/BigCodeBench/train.jsonl \
    --dataset_train_split train \
    --per_device_train_batch_size 2 \
    --learning_rate 3e-6 \
    --num_generations 2 \
    --output_dir results/grpo_rloo \
    --bf16 True \
    --use_vllm True \
    --scale_reward True \
    --gradient_filtering False \
    --gradient_filtering_threshold 0.1 \
    --logging_steps 50 \
    --use_old_model True \
    --loss_type dr_grpo
