accelerate launch --main_process_port 29600 --gpu_ids 7,8 --config_file=../recipes/zero2.yaml --num_processes 2 ../run/grpo_dp.py \
    --model_name_or_path Qwen/Qwen2.5-3B \
    --max_prompt_length 256 \
    --max_completion_length 2048 \
    --gradient_accumulation_steps 32 \ # set this to 1 (for now) for mini
    --dataset_name PATH_TO_MATH \
    --dataset_train_split train \
    --per_device_train_batch_size 4 \
    --gradient_checkpointing True \
    --num_generations 4 \
    --seed 42 \
    --learning_rate 3e-6 \
    --output_dir results/grpo_3B_dr \
    --bf16 True \
    --use_vllm True \
    --scale_reward True \
    --gradient_filtering False \
    --gradient_filtering_threshold 0.1 \
    --logging_steps 50 \
    --use_old_model True \
    --loss_type impala \ # changed from dr_grpo
    --preemptive_steps=256 \ # use this for mini, e.g. 256
    --iw False \ # use this for iw
    --read_from_file False \ # set to True AFTER the first time running iw with False (so that it can read the generations for the entire dataset from a file, written to when this is set to False)
